name: Build example
on: [push]
jobs:
  windows:
    runs-on: windows-2022
    env:
      # Workaround for https://gitlab.kitware.com/cmake/cmake/-/issues/25936
      TRANSMISSION_PREFIX: ${{ github.workspace }}/transmission-prefix
      VCPKG_MANIFEST_DIR: ${{ github.workspace }}/example
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/example/vcpkg
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows -v
  linux:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libcurl4-openssl-dev
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build linux

  macos:
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          brew install ninja
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/example/vcpkg
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build macos

  android:
    runs-on: ubuntu-24.04
    env:
      VCPKG_MANIFEST_DIR: ${{ github.workspace }}/example
      SOURCE_DATE_EPOCH: 0
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/example/vcpkg
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk
      - name: Prepare artifacts
        run: |
          mkdir ~/artifacts
          cp ./build/app/outputs/flutter-apk/*.apk ~/artifacts/
      - uses: actions/upload-artifact@v4
        with:
          name: pikatorrent-android
          path: ~/artifacts/

  ios:
    runs-on: macos-14
    env:
      # Do not target simulator
      TARGET_IOS_DEVICE: true
      IPHONEOS_DEPLOYMENT_TARGET: 12
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          brew install ninja
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/example/vcpkg
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build ios --no-codesign
